### ISSUE TITLE
Invalid syntax and unterminated string literal? Running Reptyl on Windows 11

### ISSUE THREAD

**Issue by ministerinmarin** [0ut0flin3/Reptyl#1]
![image](https://user-images.githubusercontent.com/104122030/221793133-8bb76423-cd80-40e9-833d-016a0539376f.png)
![image](https://user-images.githubusercontent.com/104122030/221793411-6e1d172b-32df-4dd0-b7a8-a60e4469b521.png)

Running Reptyl with Windows 11 using PowerShell and Python 3.10, it seems some longer strings return a different answer.

**Comment by 0ut0flin3** [comment]
> ![image](https://user-images.githubusercontent.com/104122030/221793133-8bb76423-cd80-40e9-833d-016a0539376f.png) ![image](https://user-images.githubusercontent.com/104122030/221793411-6e1d172b-32df-4dd0-b7a8-a60e4469b521.png)
> 
> Running Reptyl with Windows 11 using PowerShell and Python 3.10, it seems some longer strings return a different answer.
hello, yes this is a common error, I'm working on it. it simply means that the code generated by the request includes syntax errors. However, ask no questions but give orders. don't treat it as chatgpt but as a terminal
